# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'windows-latest'


variables:
  terraformstorageaccount: 'terraformstorage554d0a4e'
  terraformstoragerg: 'terraformrg'

steps:

- task: AzureCLI@1
  inputs:
    azureSubscription: 'VSE'
    scriptLocation: 'inlineScript'
    inlineScript: |
      # this will create Azure resource group
      call az group create --location westus --name $(terraformstoragerg)
      
      call az storage account create --name $(terraformstorageaccount) --resource-group $(terraformstoragerg) --location westus --sku Standard_LRS
      
      call az storage container create --name terraform --account-name $(terraformstorageaccount)
      
      call az storage account keys list -g $(terraformstoragerg) -n $(terraformstorageaccount)
